-- Production Grade 1 Sessions (Module ID 2)
-- Little Engineers - Complete Grade 1 Journey

INSERT OR IGNORE INTO curriculum_sessions (module_id, session_number, title, description, objectives, duration_minutes, is_project, order_number, content) VALUES
  (2, 1, 'Introduction to Electricity', 'Understanding electrical energy', '["What is electricity","Safety rules","Basic concepts"]', 60, 0, 1, '<h2>Introduction to Electricity</h2><p>Learn about electrical energy!</p>'),
  (2, 2, 'Circuits & Conductors', 'Building basic circuits', '["Circuit components","Conductors vs insulators","Complete circuit"]', 60, 0, 2, '<h2>Circuits & Conductors</h2><p>Make electricity flow!</p>'),
  (2, 3, 'Switches & Control', 'Controlling electrical flow', '["Using switches","ON/OFF control","Multiple switches"]', 60, 0, 3, '<h2>Switches & Control</h2><p>Control the power!</p>'),
  (2, 4, 'PROJECT: Light Switch', 'Build simple switch circuit', '["Wire switch","Control LED","Test circuit"]', 60, 1, 4, '<h2>PROJECT: Light Switch</h2><p>Control lights with a switch!</p>'),
  (2, 5, 'Resistors & LEDs', 'Understanding resistors', '["What is resistance","LED safety","Calculate values"]', 60, 0, 5, '<h2>Resistors & LEDs</h2><p>Protect your LEDs!</p>'),
  (2, 6, 'Series Circuits', 'Components in series', '["Wire in series","Current flow","Voltage division"]', 60, 0, 6, '<h2>Series Circuits</h2><p>Connect in a line!</p>'),
  (2, 7, 'Parallel Circuits', 'Components in parallel', '["Wire in parallel","Independent paths","Voltage same"]', 60, 0, 7, '<h2>Parallel Circuits</h2><p>Multiple paths!</p>'),
  (2, 8, 'PROJECT: Traffic Light', 'Build traffic signal', '["3 LEDs","Timed sequence","Control circuit"]', 60, 1, 8, '<h2>PROJECT: Traffic Light</h2><p>Make your own signals!</p>'),
  (2, 9, 'Breadboard Basics', 'Using a breadboard', '["What is breadboard","How connections work","Build circuits"]', 60, 0, 9, '<h2>Breadboard Basics</h2><p>No soldering needed!</p>'),
  (2, 10, 'Motors & Motion', 'Making things move', '["DC motors","Control speed","Direction change"]', 60, 0, 10, '<h2>Motors & Motion</h2><p>Make it move!</p>'),
  (2, 11, 'Gears & Mechanics', 'Mechanical advantage', '["Types of gears","Gear ratios","Speed vs torque"]', 60, 0, 11, '<h2>Gears & Mechanics</h2><p>Change speed and power!</p>'),
  (2, 12, 'PROJECT: Motor Car', 'Build motorized vehicle', '["Attach motors","Add wheels","Test drive"]', 60, 1, 12, '<h2>PROJECT: Motor Car</h2><p>Your first moving robot!</p>'),
  (2, 13, 'Introduction to Arduino', 'Meet the Arduino board', '["What is Arduino","Board parts","First connection"]', 60, 0, 13, '<h2>Introduction to Arduino</h2><p>Your robot brain!</p>'),
  (2, 14, 'Blink LED', 'First Arduino program', '["Upload code","Digital output","Timing"]', 60, 0, 14, '<h2>Blink LED</h2><p>Your first program!</p>'),
  (2, 15, 'Digital Output', 'Control multiple LEDs', '["Multiple pins","Patterns","Sequences"]', 60, 0, 15, '<h2>Digital Output</h2><p>Control many things!</p>'),
  (2, 16, 'PROJECT: Knight Rider', 'LED sequence animation', '["8 LEDs","Back and forth","Speed control"]', 60, 1, 16, '<h2>PROJECT: Knight Rider</h2><p>Cool LED animations!</p>'),
  (2, 17, 'Digital Input', 'Reading button states', '["Button input","Read pin","React to press"]', 60, 0, 17, '<h2>Digital Input</h2><p>Get information!</p>'),
  (2, 18, 'IF Statements', 'Making decisions', '["Conditional logic","IF-ELSE","Multiple conditions"]', 60, 0, 18, '<h2>IF Statements</h2><p>Let Arduino decide!</p>'),
  (2, 19, 'Variables', 'Storing information', '["What is variable","Data types","Using variables"]', 60, 0, 19, '<h2>Variables</h2><p>Remember things!</p>'),
  (2, 20, 'PROJECT: Simon Says', 'Memory game with buttons', '["Random sequence","Remember pattern","Score keeping"]', 60, 1, 20, '<h2>PROJECT: Simon Says</h2><p>Test your memory!</p>'),
  (2, 21, 'PWM Output', 'Pulse Width Modulation', '["What is PWM","Fading LEDs","Speed control"]', 60, 0, 21, '<h2>PWM Output</h2><p>Control brightness and speed!</p>'),
  (2, 22, 'Analog Input', 'Reading sensors', '["Analog vs digital","Read values","Map ranges"]', 60, 0, 22, '<h2>Analog Input</h2><p>Read sensor values!</p>'),
  (2, 23, 'Loops', 'Repeating actions', '["FOR loops","WHILE loops","Count and repeat"]', 60, 0, 23, '<h2>Loops</h2><p>Do things multiple times!</p>'),
  (2, 24, 'PROJECT: Pattern LED', 'Custom LED patterns', '["Design patterns","Use loops","Create effects"]', 60, 1, 24, '<h2>PROJECT: Pattern LED</h2><p>Your custom light show!</p>'),
  (2, 25, 'Servo Motors', 'Precise angle control', '["What is servo","Control angle","Sweep motion"]', 60, 0, 25, '<h2>Servo Motors</h2><p>Precise movement!</p>'),
  (2, 26, 'Ultrasonic Sensor', 'Measuring distance', '["How it works","Trigger and echo","Calculate distance"]', 60, 0, 26, '<h2>Ultrasonic Sensor</h2><p>Measure how far!</p>'),
  (2, 27, 'Sound & Buzzer', 'Making sounds', '["Passive buzzer","Active buzzer","Create tones"]', 60, 0, 27, '<h2>Sound & Buzzer</h2><p>Make noise!</p>'),
  (2, 28, 'PROJECT: Obstacle Sensor', 'Distance warning system', '["Measure distance","Buzzer alert","LED indicator"]', 60, 1, 28, '<h2>PROJECT: Obstacle Sensor</h2><p>Beep when close!</p>'),
  (2, 29, 'RGB LEDs', 'Mixing colors', '["Red, Green, Blue","Color mixing","Create rainbow"]', 60, 0, 29, '<h2>RGB LEDs</h2><p>Make any color!</p>'),
  (2, 30, 'Light Sensors', 'Detecting brightness', '["LDR sensor","Read light level","Auto brightness"]', 60, 0, 30, '<h2>Light Sensors</h2><p>See the light!</p>'),
  (2, 31, 'Temperature Sensor', 'Reading temperature', '["Thermometer","Celsius scale","Display temp"]', 60, 0, 31, '<h2>Temperature Sensor</h2><p>How hot is it?</p>'),
  (2, 32, 'PROJECT: Weather Monitor', 'Temperature display', '["Read temperature","Display value","Alert high/low"]', 60, 1, 32, '<h2>PROJECT: Weather Monitor</h2><p>Your weather station!</p>'),
  (2, 33, 'Functions', 'Organizing code', '["What is function","Create functions","Call functions"]', 60, 0, 33, '<h2>Functions</h2><p>Organize your code!</p>'),
  (2, 34, 'Arrays', 'Lists of values', '["What is array","Store multiple values","Access elements"]', 60, 0, 34, '<h2>Arrays</h2><p>List of things!</p>'),
  (2, 35, 'Random Numbers', 'Creating randomness', '["Generate random","Random range","Dice game"]', 60, 0, 35, '<h2>Random Numbers</h2><p>Surprise values!</p>'),
  (2, 36, 'PROJECT: Electronic Dice', 'Digital dice game', '["Random 1-6","Display LEDs","Roll button"]', 60, 1, 36, '<h2>PROJECT: Electronic Dice</h2><p>Roll the dice!</p>'),
  (2, 37, 'Final Project Planning', 'Choose your project', '["Project ideas","Plan design","Gather materials"]', 60, 0, 37, '<h2>Final Project Planning</h2><p>Plan your creation!</p>'),
  (2, 38, 'Design Phase', 'Draw and plan', '["Circuit diagram","Component list","Build plan"]', 60, 0, 38, '<h2>Design Phase</h2><p>Design your project!</p>'),
  (2, 39, 'Building Phase 1', 'Start construction', '["Assemble parts","Wire connections","Test components"]', 60, 0, 39, '<h2>Building Phase 1</h2><p>Start building!</p>'),
  (2, 40, 'Building Phase 2', 'Continue building', '["Complete wiring","Add sensors","Mount components"]', 60, 0, 40, '<h2>Building Phase 2</h2><p>Keep building!</p>'),
  (2, 41, 'Programming Phase', 'Write the code', '["Plan logic","Write code","Test functions"]', 60, 0, 41, '<h2>Programming Phase</h2><p>Code it!</p>'),
  (2, 42, 'Testing Phase', 'Test and debug', '["Find problems","Fix bugs","Improve performance"]', 60, 0, 42, '<h2>Testing Phase</h2><p>Make it work!</p>'),
  (2, 43, 'Decoration Phase', 'Make it beautiful', '["Add decorations","Paint/color","Final touches"]', 60, 0, 43, '<h2>Decoration Phase</h2><p>Make it pretty!</p>'),
  (2, 44, 'Practice Presentation', 'Prepare to show', '["Explain project","Demo features","Answer questions"]', 60, 0, 44, '<h2>Practice Presentation</h2><p>Get ready to share!</p>'),
  (2, 45, 'FINAL PROJECT: My Creative Robot', 'Complete your masterpiece', '["Final testing","Perfect details","Ready to present"]', 60, 1, 45, '<h2>FINAL PROJECT</h2><p>Your amazing creation!</p>'),
  (2, 46, 'Project Exhibition', 'Show your work', '["Setup display","Present project","Celebrate success"]', 60, 0, 46, '<h2>Project Exhibition</h2><p>Show everyone!</p>'),
  (2, 47, 'Awards Ceremony', 'Receive recognition', '["Best projects","Participation awards","Team celebration"]', 60, 0, 47, '<h2>Awards Ceremony</h2><p>You did it!</p>'),
  (2, 48, 'Graduation Ceremony', 'Complete Grade 1', '["Receive certificate","Group photo","Plan Grade 2"]', 60, 0, 48, '<h2>Graduation Ceremony</h2><p>Little Engineer complete!</p>');
