-- Production Grade 2 Sessions (Module ID 3)
-- Smart Robots - Complete Grade 2 Journey

INSERT OR IGNORE INTO curriculum_sessions (module_id, session_number, title, description, objectives, duration_minutes, is_project, order_number, content) VALUES
  (3, 1, 'Touch Sensor Deep Dive', 'Advanced touch sensing', '["Multiple touch points","Pressure sensitivity","Build touch interface"]', 60, 0, 1, '<h2>Advanced Touch Sensing</h2><p>Make robots respond to touch!</p>'),
  (3, 2, 'Light Sensors & LDR', 'Light dependent resistors', '["Measure brightness","Auto-adjust lighting","Build day/night detector"]', 60, 0, 2, '<h2>Light Sensors</h2><p>Detect light levels!</p>'),
  (3, 3, 'Sound Level Detection', 'Measuring sound intensity', '["Detect sound levels","Create noise meter","Build sound alarm"]', 60, 0, 3, '<h2>Sound Detection</h2><p>Measure how loud it is!</p>'),
  (3, 4, 'PROJECT: Touch Lamp', 'Touch-activated LED lamp', '["Build circuit","Test sensitivity","Create lamp"]', 60, 1, 4, '<h2>PROJECT: Touch Lamp</h2><p>Touch to light up!</p>'),
  (3, 5, 'Temperature Sensors', 'Measuring temperature', '["Use thermistor","Read temperature","Display values"]', 60, 0, 5, '<h2>Temperature Sensing</h2><p>How hot or cold?</p>'),
  (3, 6, 'Humidity Sensors', 'Detecting moisture', '["Measure humidity","Understand dew point","Build weather station"]', 60, 0, 6, '<h2>Humidity Sensing</h2><p>Detect moisture!</p>'),
  (3, 7, 'Distance Sensors', 'Measuring distance', '["Use ultrasonic","Measure range","Detect proximity"]', 60, 0, 7, '<h2>Distance Measurement</h2><p>How far is it?</p>'),
  (3, 8, 'PROJECT: Parking Sensor', 'Distance-based warning system', '["Detect distance","Sound buzzer","LED indicators"]', 60, 1, 8, '<h2>PROJECT: Park Assist</h2><p>Help park safely!</p>'),
  (3, 9, 'Motion Sensors', 'Detecting movement', '["Use PIR sensor","Detect motion","Build alarm"]', 60, 0, 9, '<h2>Motion Detection</h2><p>Sense movement!</p>'),
  (3, 10, 'Tilt & Orientation', 'Measuring tilt and angle', '["Use tilt sensor","Detect orientation","Build level indicator"]', 60, 0, 10, '<h2>Tilt Sensing</h2><p>Which way is up?</p>'),
  (3, 11, 'Gas & Air Quality', 'Detecting gases', '["Use gas sensor","Measure air quality","Build safety alarm"]', 60, 0, 11, '<h2>Gas Detection</h2><p>Keep air safe!</p>'),
  (3, 12, 'PROJECT: Weather Station', 'Multi-sensor weather monitor', '["Combine sensors","Display data","Track weather"]', 60, 1, 12, '<h2>PROJECT: Weather Station</h2><p>Your own weather center!</p>'),
  (3, 13, 'What is Automation?', 'Introduction to automated systems', '["Understand automation","See examples","Plan automated system"]', 60, 0, 13, '<h2>Automation Basics</h2><p>Make things work automatically!</p>'),
  (3, 14, 'Automatic Lights', 'Light sensing automation', '["Auto on/off","Brightness control","Energy saving"]', 60, 0, 14, '<h2>Smart Lighting</h2><p>Lights that think!</p>'),
  (3, 15, 'Automatic Doors', 'Motion-activated opening', '["Detect presence","Open/close","Safety features"]', 60, 0, 15, '<h2>Auto Doors</h2><p>Doors that open themselves!</p>'),
  (3, 16, 'PROJECT: Smart Room', 'Automated room lighting', '["Wire system","Program automation","Test scenarios"]', 60, 1, 16, '<h2>PROJECT: Smart Room</h2><p>Automate your space!</p>'),
  (3, 17, 'Temperature Control', 'Thermostat automation', '["Set temperature","Control heating","Auto adjust"]', 60, 0, 17, '<h2>Temperature Control</h2><p>Perfect temperature!</p>'),
  (3, 18, 'Fan Automation', 'Auto fan control', '["Temperature based","Speed control","Energy efficient"]', 60, 0, 18, '<h2>Smart Fans</h2><p>Cool when needed!</p>'),
  (3, 19, 'Water Level Control', 'Automatic water management', '["Detect water level","Auto pump","Overflow prevention"]', 60, 0, 19, '<h2>Water Control</h2><p>Manage water automatically!</p>'),
  (3, 20, 'PROJECT: Plant Waterer', 'Auto plant watering system', '["Moisture sensor","Water pump","Scheduling"]', 60, 1, 20, '<h2>PROJECT: Plant Care</h2><p>Auto water plants!</p>'),
  (3, 21, 'Light Following', 'Robot follows brightest light', '["Two light sensors","Compare values","Steer toward light"]', 60, 0, 21, '<h2>Light Following</h2><p>Seek the light!</p>'),
  (3, 22, 'Line Following Advanced', 'Multiple sensor line tracking', '["Array sensors","PID control","Fast tracking"]', 60, 0, 22, '<h2>Line Following</h2><p>Stay on track!</p>'),
  (3, 23, 'Obstacle Avoidance', 'Navigate around obstacles', '["Detect obstacles","Change path","Complete route"]', 60, 0, 23, '<h2>Avoid Obstacles</h2><p>Do not crash!</p>'),
  (3, 24, 'PROJECT: Maze Solver', 'Robot navigates maze', '["Build maze","Program logic","Complete course"]', 60, 1, 24, '<h2>PROJECT: Maze Bot</h2><p>Solve the maze!</p>'),
  (3, 25, 'Wired Communication', 'Serial and UART basics', '["Send data","Receive data","Two-way talk"]', 60, 0, 25, '<h2>Wired Communication</h2><p>Robots talk through wires!</p>'),
  (3, 26, 'Wireless Basics', 'Introduction to wireless', '["Radio waves","Frequencies","Range"]', 60, 0, 26, '<h2>Wireless Basics</h2><p>Communication without wires!</p>'),
  (3, 27, 'Infrared Control', 'IR remote control', '["IR transmitter","IR receiver","Send commands"]', 60, 0, 27, '<h2>IR Control</h2><p>Invisible commands!</p>'),
  (3, 28, 'PROJECT: IR Remote Bot', 'Robot with IR remote', '["Build receiver","Program commands","Test control"]', 60, 1, 28, '<h2>PROJECT: IR Bot</h2><p>Control with remote!</p>'),
  (3, 29, 'Bluetooth Basics', 'Wireless Bluetooth control', '["Pair devices","Send data","Receive commands"]', 60, 0, 29, '<h2>Bluetooth Control</h2><p>Phone controlled!</p>'),
  (3, 30, 'App Control', 'Mobile app interface', '["Use app","Send commands","Get feedback"]', 60, 0, 30, '<h2>App Control</h2><p>Control from phone!</p>'),
  (3, 31, 'Data Logging', 'Recording sensor data', '["Collect data","Store values","Analyze trends"]', 60, 0, 31, '<h2>Data Logging</h2><p>Save information!</p>'),
  (3, 32, 'PROJECT: Data Logger', 'Environmental data recorder', '["Multi sensors","Store data","Display graphs"]', 60, 1, 32, '<h2>PROJECT: Logger</h2><p>Track everything!</p>'),
  (3, 33, 'Display Screens', 'LCD and OLED displays', '["Show text","Display values","Create menus"]', 60, 0, 33, '<h2>Display Screens</h2><p>Show information!</p>'),
  (3, 34, 'User Interface', 'Buttons and menus', '["Navigate menus","Select options","Configure settings"]', 60, 0, 34, '<h2>User Interface</h2><p>Easy to use!</p>'),
  (3, 35, 'Alarm Systems', 'Security and alerts', '["Detect intrusion","Sound alarm","Send alert"]', 60, 0, 35, '<h2>Alarm Systems</h2><p>Stay secure!</p>'),
  (3, 36, 'PROJECT: Security System', 'Complete security solution', '["Multiple sensors","Display status","Alert system"]', 60, 1, 36, '<h2>PROJECT: Security</h2><p>Protect your space!</p>'),
  (3, 37, 'Project Selection', 'Choose capstone project', '["Review options","Choose project","Form team"]', 60, 0, 37, '<h2>Project Selection</h2><p>Pick your challenge!</p>'),
  (3, 38, 'Research & Planning', 'Deep project planning', '["Research topic","Design system","Create timeline"]', 60, 0, 38, '<h2>Planning Phase</h2><p>Plan thoroughly!</p>'),
  (3, 39, 'Component Selection', 'Choose right parts', '["Select sensors","Choose actuators","Order materials"]', 60, 0, 39, '<h2>Select Components</h2><p>Pick the best parts!</p>'),
  (3, 40, 'Prototype Building', 'Build initial version', '["Assemble prototype","Test basic functions","Identify issues"]', 60, 0, 40, '<h2>Prototype</h2><p>Build first version!</p>'),
  (3, 41, 'Circuit Design', 'Design complete circuit', '["Draw schematic","Plan layout","Build circuit"]', 60, 0, 41, '<h2>Circuit Design</h2><p>Design electronics!</p>'),
  (3, 42, 'Software Development', 'Write complete code', '["Write algorithms","Test functions","Debug code"]', 60, 0, 42, '<h2>Programming</h2><p>Write the code!</p>'),
  (3, 43, 'Integration Testing', 'Test all together', '["Hardware + software","Full system test","Fix bugs"]', 60, 0, 43, '<h2>Integration</h2><p>Make it all work!</p>'),
  (3, 44, 'Documentation', 'Document the project', '["Write manual","Create diagrams","Record video"]', 60, 0, 44, '<h2>Documentation</h2><p>Explain your work!</p>'),
  (3, 45, 'FINAL PROJECT: Smart Automation System', 'Complete automation project', '["Finalize project","Perfect details","Prepare demo"]', 60, 1, 45, '<h2>FINAL PROJECT</h2><p>Your masterpiece!</p>'),
  (3, 46, 'Project Exhibition', 'Public demonstration', '["Setup booth","Demo project","Answer questions"]', 60, 0, 46, '<h2>Exhibition</h2><p>Show the world!</p>'),
  (3, 47, 'Awards & Recognition', 'Recognition ceremony', '["Present awards","Celebrate success","Share achievements"]', 60, 0, 47, '<h2>Awards</h2><p>You are amazing!</p>'),
  (3, 48, 'Graduation & Next Steps', 'Complete Grade 2 journey', '["Receive certificate","Plan Grade 3","Celebrate!"]', 60, 0, 48, '<h2>Graduation!</h2><p>Smart Robots Master!</p>');
